export interface ContactFromServer {
    accountContacts: string[]
    adate: string
    anonymized: string
    bounced_date: string
    bounced_hard: string
    bounced_soft: string
    cdate: string
    contactTags: string[]
    created_by: string
    created_timestamp: string
    created_utc_timestamp: string
    deleted: string
    deleted_at: string
    edate: string
    email: string
    email_domain: string
    email_empty: string
    email_local: string
    firstName: string
    gravatar: string
    hash: string
    id: string
    ip: string
    lastName: string
    links: {
        accountContacts: string
        automationEntryCounts: string
        bounceLogs: string
        contactAutomations: string
        contactData: string
        contactDeals: string
        contactGoals: string
        contactLists: string
        contactLogs: string
        contactTags: string
        deals: string
        fieldValues: string
        geoIps: string
        notes: string
        organization: string
        plusAppend: string
        scoreValues: string
        trackingLogs: string
    }
    organization: string
    orgid: string
    orgname: string
    phone: string
    rating_tstamp: string
    scoreValues: string[]
    segmentio_id: string
    sentcnt: string
    socialdata_lastcheck: string
    ua: string
    udate: string
    updated_by: string
    updated_timestamp: string
    updated_utc_timestamp: string
}